name: CI Frontend

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build Next.js
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          # Estas variables (dummy o reales) son requeridas para que el build SSG no falle
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
          JWT_SECRET: "dummy_secret_ci_key_32_characters_minimum"
          API_SECRET: "dummy_webhook_secret_for_ci_build"
